package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/zakyyudha/mtmr-lyrx/internal/display"
)

func newMTMRConfigCommand(opts *Options) *cobra.Command {
	var (
		install   bool
		stateFile string
		width     int
	)

	cmd := &cobra.Command{
		Use:   "mtmr-config",
		Short: "Print MTMR shellScriptTitledButton JSON snippet for Touch Bar lyrics",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := loadConfig(opts)
			if err != nil {
				return err
			}

			resolvedState := display.ResolveStateFile(cfg.Display)
			if stateFile != "" {
				resolvedState = stateFile
			}

			refreshInterval := 0.5

			pixelWidth := width
			if pixelWidth <= 0 {
				pixelWidth = 380
			}

			placeholder := cfg.Display.Placeholder
			if placeholder == "" {
				placeholder = "♪"
			}

			if install {
				return installHelperScript(cmd, resolvedState, placeholder, pixelWidth, refreshInterval)
			}

			// Default: print inline snippet
			source := buildInlineSource(resolvedState, placeholder)
			snippet := map[string]interface{}{
				"bordered":        false,
				"type":            "shellScriptTitledButton",
				"width":           pixelWidth,
				"refreshInterval": refreshInterval,
				"source": map[string]string{
					"inline": source,
				},
			}

			data, err := json.MarshalIndent(snippet, "", "  ")
			if err != nil {
				return fmt.Errorf("marshal JSON: %w", err)
			}
			fmt.Fprintln(cmd.OutOrStdout(), string(data))
			return nil
		},
	}

	cmd.Flags().BoolVar(&install, "install", false, "install helper script and print snippet referencing it")
	cmd.Flags().StringVar(&stateFile, "state-file", "", "override state file path in snippet")
	cmd.Flags().IntVar(&width, "width", 380, "Touch Bar item pixel width")

	return cmd
}

// buildInlineSource builds the MTMR source command that reads the state file.
// Uses absolute paths and avoids network calls.
func buildInlineSource(stateFile string, placeholder string) string {
	// Shell-safe: use single quotes around the path, escape any single quotes in path
	safePath := strings.ReplaceAll(stateFile, "'", "'\\''")
	safePlaceholder := strings.ReplaceAll(placeholder, "'", "'\\''")
	return fmt.Sprintf("/bin/bash -lc 'cat %s 2>/dev/null || /usr/bin/printf '\\''%s'\\'''",
		"'"+safePath+"'", safePlaceholder)
}

// installHelperScript creates ~/.config/mtmr-lyrx/read-lyrics.sh and prints
// a JSON snippet that references it.
func installHelperScript(cmd *cobra.Command, stateFile, placeholder string, pixelWidth int, refreshInterval float64) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("get home dir: %w", err)
	}

	scriptDir := filepath.Join(home, ".config", "mtmr-lyrx")
	scriptPath := filepath.Join(scriptDir, "read-lyrics.sh")

	if err := os.MkdirAll(scriptDir, 0755); err != nil {
		return fmt.Errorf("create script dir: %w", err)
	}

	scriptContent := fmt.Sprintf(`#!/bin/bash
# mtmr-lyrx helper script — reads current lyric line for MTMR Touch Bar
# Generated by: mtmr-lyrx mtmr-config --install
state_file=%q
if [[ -r "$state_file" ]]; then
  /bin/cat "$state_file"
else
  /usr/bin/printf %q
fi
`, stateFile, placeholder)

	if err := os.WriteFile(scriptPath, []byte(scriptContent), 0755); err != nil {
		return fmt.Errorf("write helper script: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "# Installed helper script: %s\n\n", scriptPath)

	snippet := map[string]interface{}{
		"bordered":        false,
		"type":            "shellScriptTitledButton",
		"width":           pixelWidth,
		"refreshInterval": refreshInterval,
		"source": map[string]string{
			"inline": fmt.Sprintf("/bin/bash %s", scriptPath),
		},
	}

	data, err := json.MarshalIndent(snippet, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal JSON: %w", err)
	}
	fmt.Fprintln(cmd.OutOrStdout(), string(data))
	return nil
}
